# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160302_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='gathered',
            field=models.IntegerField(editable=False),
        ),
    ]
