# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20160302_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gathered',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
