# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20160302_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gathered',
            field=models.IntegerField(default=0),
        ),
    ]
